### ISSUE TITLE
Turn on even if we might be behind a NAT

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p-autonat#73]
We added a feature to only turn on if another AutoNAT node tells us we're not behind a NAT. Unfortunately, this makes it painful to bootstrap a network.

The original motivation was that we didn't want a cluster of nodes behind the same firewall to determine that they're all reachable. However, I'm not sure if that's actually effective. All it takes is for a single node to be reachable for the entire cluster to say "I'm reachable!".

Instead, we should probably just implement https://github.com/libp2p/go-libp2p-autonat/issues/47.

**Comment by willscott** [comment]
A potentially complementary approach to the point mentioned here is that it could be useful for nodes to be running the autonat service in at least a limited level until they they begin to believe they are in a private situation.

Currently, there are anticipated issues with a private network bootstrapping correctly, because no nodes will initially be running an autonat service in their default auto-detect mode.
